/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AInput: typeof import('ant-design-vue/es')['Input']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    Category: typeof import('./src/components/category.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Input: typeof import('./src/components/input.vue')['default']
    Item: typeof import('./src/components/item.vue')['default']
    TodoList: typeof import('./src/components/todoList.vue')['default']
  }
}
